---
apiVersion: v1
kind: Namespace
metadata:
  name: storage-example
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: outscale-bsu
provisioner: bsu.csi.osc.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-claim
  namespace: storage-example
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: outscale-bsu
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app
  namespace: storage-example
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /data
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: my-claim
