---
- name: Destroy 2048 example service
  hosts: control-plane-0
  tasks:
    - name: Destroy 2048 service
      command:
        cmd: "kubectl delete -f -"
        stdin: "{{ lookup('file', '2048.yaml') }}"
